#!/usr/bin/env python3
"""Generate docs/DOCUMENTATION_INDEX.md from document front matter.

The index was previously hand-maintained and had fallen 30 documents behind. It is now
derived data: run this after adding or retiring a document, and scripts/validate_docs.py
will fail the build if it is stale.
"""
from __future__ import annotations
import pathlib, re, sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from validate_docs import ROOT, collect, parse_front_matter  # noqa: E402

READING_ORDER = [
    "README.md",
    "docs/vision/PRODUCT_VISION.md",
    "docs/vision/PRINCIPLES.md",
    "docs/spec/AUTHORITY_MODEL.md",
    "docs/GLOSSARY.md",
    "docs/architecture/SYSTEM_ARCHITECTURE.md",
    "docs/agents/ORGANIZATION.md",
    "docs/agents/UNIVERSAL_AGENT_LOOP.md",
    "docs/workflows/END_TO_END_SDLC.md",
]

SECTIONS = [
    ("Foundations", "Constitutional and meta-specification. Tier 0.",
     lambda fm, rel: fm["type"] in ("principle", "spec")),
    ("Architecture decisions", "Immutable once accepted. Reverse by superseding. Tier 1.",
     lambda fm, rel: fm["type"] == "adr"),
    ("Product requirements", "Human-readable requirements. Tier 2.",
     lambda fm, rel: fm["type"] == "prd"),
    ("Agent development specifications", "Machine projections of approved intent. Tier 2.",
     lambda fm, rel: fm["type"] == "ads"),
    ("Design", "Normative platform design. Tier 2.",
     lambda fm, rel: fm["type"] == "design"),
    ("Rules", "Policies block when violated; standards inform review. Tier 3.",
     lambda fm, rel: fm["type"] in ("policy", "standard")),
    ("Reference", "Non-normative. Carries no authority in conflict resolution.",
     lambda fm, rel: fm["type"] in ("guide", "example")),
]

AREA = {
    "docs/architecture": "Architecture", "docs/agents": "Agents",
    "docs/memory": "Memory", "docs/context": "Context",
    "docs/workflows": "Workflows", "docs/github": "GitHub control plane",
    "docs/security": "Security", "docs/operations": "Operations",
    "docs/ads": "Specification system",
}


def title_of(path: pathlib.Path) -> str:
    if path.suffix in (".yaml", ".yml"):
        fm, _ = parse_front_matter(path)
        return fm.get("title", path.stem)
    for line in path.read_text().splitlines():
        if line.startswith("# "):
            # Strip a leading "ADR-001 — " / "PRD-002 — "; the ID has its own column.
            return re.sub(r"^(?:ADR|PRD|ADS|POL|STD)-\d+\s*[—-]\s*", "", line[2:].strip())
    return path.stem


def main() -> int:
    entries = []
    for path, rel in collect():
        fm, ok = parse_front_matter(path)
        if not ok or fm is None:
            print(f"skipping unparseable {rel}", file=sys.stderr)
            continue
        entries.append((rel, fm, title_of(path)))

    # The index is itself a document and carries front matter. Preserve any
    # existing values so regenerating does not churn the review date.
    index_path = ROOT / "docs" / "DOCUMENTATION_INDEX.md"
    prior = {}
    if index_path.exists():
        fm, ok = parse_front_matter(index_path)
        if ok and fm:
            prior = fm

    out = ["---",
           "id: GUIDE-DOCUMENTATION-INDEX",
           "type: guide",
           "tier: null",
           "status: draft",
           f"version: {prior.get('version', 1)}",
           "owner: human.cto",
           "human_approved: false",
           "approved_by: null",
           "approved_on: null",
           "approval_record: null",
           "supersedes: null",
           "superseded_by: null",
           f"last_reviewed: {prior.get('last_reviewed', '2026-08-29')}",
           "---", "",
           "# Documentation Index", "",
           "<!-- Generated by scripts/build_index.py. Do not edit by hand. -->", "",
           "Authority tiers are defined in `docs/spec/AUTHORITY_MODEL.md`. Only `approved` and",
           "`accepted` artifacts carry their tier's authority; `draft` carries none.", "",
           "## Reading order", ""]
    for i, rel in enumerate(READING_ORDER, 1):
        name = "README" if rel == "README.md" else title_of(ROOT / rel)
        out.append(f"{i}. [{name}]({rel})")
    out.append("")

    for heading, blurb, match in SECTIONS:
        rows = sorted((e for e in entries if match(e[1], e[0])), key=lambda e: e[0])
        if not rows:
            continue
        out += [f"## {heading}", "", blurb, "",
                "| ID | Document | Status | Path |", "| --- | --- | --- | --- |"]
        last_area = None
        for rel, fm, title in rows:
            area = AREA.get(str(pathlib.PurePath(rel).parent))
            if heading == "Design" and area != last_area:
                out.append(f"| | **{area}** | | |")
                last_area = area
            out.append(f"| `{fm['id']}` | {title} | `{fm['status']}` | [{rel}]({rel}) |")
        out.append("")

    out += ["## Registries", "",
            "Machine-readable vocabulary. See `docs/spec/REGISTRIES.md`.", "",
            "| Registry | Defines |", "| --- | --- |",
            "| [gates.yaml](../.agentic/registries/gates.yaml) | Human-approval gate IDs |",
            "| [hook-points.yaml](../.agentic/registries/hook-points.yaml) | Lifecycle boundaries |",
            "| [states.yaml](../.agentic/registries/states.yaml) | State vocabularies |", "",
            "## Schemas", "",
            "Illustrative payload fragments. Exempt from front matter.", ""]
    for p in sorted(ROOT.glob("docs/schemas/*.yaml")):
        rel = str(p.relative_to(ROOT))
        out.append(f"- [{p.name}]({rel.removeprefix('docs/')})")
    out.append("")

    (ROOT / "docs" / "DOCUMENTATION_INDEX.md").write_text("\n".join(out))
    print(f"index: {len(entries)} documents")
    return 0


if __name__ == "__main__":
    sys.exit(main())
